# Percy configuration for visual regression testing
version: 2

discovery:
  allowed-hostnames:
    - localhost

snapshot:
  widths:
    - 375   # Mobile
    - 768   # Tablet
    - 1280  # Desktop
    - 1920  # Large Desktop
  
  min-height: 1024
  
  percy-css: |
    /* Hide dynamic content that changes between runs */
    [data-testid*="timestamp"],
    [data-testid*="time"],
    .animate-pulse,
    .animate-spin {
      visibility: hidden !important;
    }
    
    /* Ensure consistent font rendering */
    * {
      -webkit-font-smoothing: antialiased;
      -moz-osx-font-smoothing: grayscale;
    }

static-snapshots:
  base-url: http://localhost:6006
  snapshot-files: '**/*.html'
  ignore-files: 
    - 'iframe.html'

# Storybook integration
storybook:
  allowed-hostnames:
    - localhost
  
  # Skip stories that are not suitable for visual testing
  skip-stories:
    - '**/Loading'
    - '**/Error'
    - '**/*Interactive*'

# CI/CD integration
agent:
  asset-discovery:
    network-idle-timeout: 750
    
# Comparison settings
comparison:
  threshold: 0.1  # 0.1% threshold for changes
  
# Project settings
project-id: your-percy-project-id