"""
API router for LLM-generated learning content.

Handles content generation for reading materials, concept explanations,
and other educational content using the LLM service.
"""

import logging
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel, Field

from src.adapters.api.models.common import ErrorResponse
from src.adapters.api.dependencies import get_current_user_id
from src.adapters.services.llm_service import LLMService, create_llm_service


logger = logging.getLogger(__name__)

router = APIRouter(
    prefix="/api/v1/content",
    tags=["content"],
    responses={
        400: {"model": ErrorResponse, "description": "Bad Request"},
        401: {"model": ErrorResponse, "description": "Unauthorized"},
        500: {"model": ErrorResponse, "description": "Internal Server Error"},
    },
)


# Request/Response Models
class GenerateContentRequest(BaseModel):
    """Request model for content generation."""
    topic: str = Field(..., description="The topic to generate content for")
    task_title: str = Field(..., description="The title of the learning task")
    task_type: str = Field(..., description="Type of task: reading, exercise, project, quiz, video")
    skill_level: str = Field(default="intermediate", description="Learner skill level: beginner, intermediate, advanced")
    technology: Optional[str] = Field(None, description="The technology/language context")
    requirements: list[str] = Field(default_factory=list, description="Task requirements to cover")


class GenerateContentResponse(BaseModel):
    """Response model for generated content."""
    content: str = Field(..., description="The generated learning content in markdown format")
    summary: str = Field(..., description="Brief summary of the content")
    key_concepts: list[str] = Field(default_factory=list, description="Key concepts covered")
    code_examples: list[dict] = Field(default_factory=list, description="Code examples if applicable")
    practice_suggestions: list[str] = Field(default_factory=list, description="Suggestions for practice")
    generated: bool = Field(default=True, description="Whether content was generated by LLM")


class ExplainConceptRequest(BaseModel):
    """Request model for concept explanation."""
    concept: str = Field(..., description="The concept to explain")
    skill_level: str = Field(default="intermediate", description="Learner skill level")
    context: Optional[str] = Field(None, description="Additional context for the explanation")


class ExplainConceptResponse(BaseModel):
    """Response model for concept explanation."""
    explanation: str = Field(..., description="The concept explanation")
    examples: list[str] = Field(default_factory=list, description="Examples illustrating the concept")
    related_concepts: list[str] = Field(default_factory=list, description="Related concepts to explore")


# LLM Service instance (singleton pattern)
_llm_service: Optional[LLMService] = None


def get_llm_service() -> LLMService:
    """Get or create LLM service instance."""
    global _llm_service
    if _llm_service is None:
        _llm_service = create_llm_service()
    return _llm_service


@router.post(
    "/generate",
    response_model=GenerateContentResponse,
    summary="Generate learning content",
    description="""
    Generate rich learning content for a task using LLM.
    
    This endpoint creates detailed educational content including:
    - Comprehensive explanations
    - Code examples
    - Key concepts
    - Practice suggestions
    
    The content is tailored to the learner's skill level and the specific topic.
    """,
)
async def generate_content(
    request: GenerateContentRequest,
    user_id: str = Depends(get_current_user_id),
) -> GenerateContentResponse:
    """Generate learning content for a task."""
    try:
        logger.info(f"Generating content for topic '{request.topic}' for user {user_id}")
        
        llm_service = get_llm_service()
        
        # Build the prompt for content generation
        system_prompt = f"""You are an expert programming instructor creating educational content for {request.skill_level} learners.

Your content should be:
- Clear, engaging, and well-structured
- Appropriate for {request.skill_level} level learners
- Practical with real-world examples
- Include code examples where relevant
- Use markdown formatting for readability

Format your response as follows:
1. Start with a brief introduction (2-3 sentences)
2. Explain the core concepts with clear headings
3. Include code examples with explanations
4. Provide practical tips and best practices
5. End with a summary of key takeaways"""

        # Build requirements context
        requirements_text = ""
        if request.requirements:
            requirements_text = "\n\nKey topics to cover:\n" + "\n".join(f"- {req}" for req in request.requirements)
        
        tech_context = f" in {request.technology}" if request.technology else ""
        
        prompt = f"""Create comprehensive learning content for the following task:

Task Title: {request.task_title}
Topic: {request.topic}{tech_context}
Task Type: {request.task_type}
Skill Level: {request.skill_level}
{requirements_text}

Please provide detailed, educational content that helps the learner understand and master this topic. Include practical code examples and explanations."""

        # Generate content using LLM
        response = await llm_service.generate(prompt, system_prompt)
        
        if not response.success:
            logger.warning(f"LLM generation failed: {response.error}")
            # Return fallback content
            return _generate_fallback_content(request)
        
        # Parse the generated content
        content = response.content
        
        # Extract key concepts from the content
        key_concepts = _extract_key_concepts(content, request.requirements)
        
        # Extract code examples
        code_examples = _extract_code_examples(content)
        
        # Generate practice suggestions
        practice_suggestions = _generate_practice_suggestions(request.topic, request.task_type)
        
        # Create summary
        summary = _create_summary(request.topic, request.task_type, request.skill_level)
        
        return GenerateContentResponse(
            content=content,
            summary=summary,
            key_concepts=key_concepts,
            code_examples=code_examples,
            practice_suggestions=practice_suggestions,
            generated=True
        )
        
    except Exception as e:
        logger.error(f"Error generating content: {e}", exc_info=True)
        # Return fallback content instead of failing
        return _generate_fallback_content(request)


@router.post(
    "/explain",
    response_model=ExplainConceptResponse,
    summary="Explain a concept",
    description="""
    Get a detailed explanation of a programming concept.
    
    The explanation is tailored to the learner's skill level and includes
    examples and related concepts to explore.
    """,
)
async def explain_concept(
    request: ExplainConceptRequest,
    user_id: str = Depends(get_current_user_id),
) -> ExplainConceptResponse:
    """Explain a programming concept."""
    try:
        logger.info(f"Explaining concept '{request.concept}' for user {user_id}")
        
        llm_service = get_llm_service()
        
        # Use the LLM service's explain_concept method
        explanation = await llm_service.explain_concept(
            request.concept,
            request.skill_level
        )
        
        # Generate examples and related concepts
        examples = _generate_concept_examples(request.concept)
        related_concepts = _generate_related_concepts(request.concept)
        
        return ExplainConceptResponse(
            explanation=explanation,
            examples=examples,
            related_concepts=related_concepts
        )
        
    except Exception as e:
        logger.error(f"Error explaining concept: {e}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to explain concept: {str(e)}"
        )


def _generate_fallback_content(request: GenerateContentRequest) -> GenerateContentResponse:
    """Generate fallback content when LLM is unavailable."""
    tech_context = f" in {request.technology}" if request.technology else ""
    
    content = f"""# {request.task_title}

## Introduction

This lesson covers **{request.topic}**{tech_context}. Understanding this concept is essential for your development journey.

## Key Concepts

"""
    
    if request.requirements:
        for i, req in enumerate(request.requirements, 1):
            content += f"### {i}. {req}\n\n"
            content += f"This concept involves understanding {req.lower()}. Take time to explore this topic through the provided resources and practice exercises.\n\n"
    else:
        content += f"The main focus of this lesson is to help you understand {request.topic} and how to apply it in real-world scenarios.\n\n"
    
    content += """## Practice Tips

- Start with the basics and build up gradually
- Try to implement what you learn in small projects
- Don't hesitate to revisit concepts if needed
- Practice regularly to reinforce your understanding

## Summary

Take your time with this material. Understanding these concepts well will help you become a more effective developer.
"""
    
    return GenerateContentResponse(
        content=content,
        summary=f"Learn about {request.topic}{tech_context}",
        key_concepts=request.requirements[:5] if request.requirements else [request.topic],
        code_examples=[],
        practice_suggestions=[
            "Review the provided resources",
            "Try implementing a small example",
            "Practice with variations of the concept"
        ],
        generated=False
    )


def _extract_key_concepts(content: str, requirements: list[str]) -> list[str]:
    """Extract key concepts from generated content."""
    # Use requirements as base concepts
    concepts = requirements[:5] if requirements else []
    
    # Try to extract additional concepts from headers
    lines = content.split('\n')
    for line in lines:
        if line.startswith('## ') or line.startswith('### '):
            concept = line.lstrip('#').strip()
            if concept and concept not in concepts and len(concepts) < 8:
                concepts.append(concept)
    
    return concepts


def _extract_code_examples(content: str) -> list[dict]:
    """Extract code examples from generated content."""
    examples = []
    lines = content.split('\n')
    in_code_block = False
    current_code = []
    current_language = ""
    
    for line in lines:
        if line.startswith('```') and not in_code_block:
            in_code_block = True
            current_language = line[3:].strip() or "javascript"
            current_code = []
        elif line.startswith('```') and in_code_block:
            in_code_block = False
            if current_code:
                examples.append({
                    "language": current_language,
                    "code": '\n'.join(current_code)
                })
        elif in_code_block:
            current_code.append(line)
    
    return examples[:5]  # Limit to 5 examples


def _generate_practice_suggestions(topic: str, task_type: str) -> list[str]:
    """Generate practice suggestions based on topic and task type."""
    suggestions = [
        f"Practice implementing {topic} in a small project",
        "Try explaining the concept to someone else",
        "Write code examples without looking at references",
    ]
    
    if task_type == "exercise":
        suggestions.extend([
            "Complete the coding exercise multiple times",
            "Try solving the problem with different approaches"
        ])
    elif task_type == "project":
        suggestions.extend([
            "Plan your project structure before coding",
            "Break down the project into smaller tasks"
        ])
    elif task_type == "reading":
        suggestions.extend([
            "Take notes while reading",
            "Summarize key points in your own words"
        ])
    
    return suggestions[:5]


def _create_summary(topic: str, task_type: str, skill_level: str) -> str:
    """Create a brief summary of the content."""
    return f"A {skill_level}-level {task_type} covering {topic}. This content will help you understand and apply the concepts in practical scenarios."


def _generate_concept_examples(concept: str) -> list[str]:
    """Generate examples for a concept."""
    return [
        f"A practical example of {concept} in action",
        f"How {concept} is used in real-world applications",
        f"Common patterns involving {concept}"
    ]


def _generate_related_concepts(concept: str) -> list[str]:
    """Generate related concepts to explore."""
    # This would ideally use a knowledge graph or LLM
    return [
        f"Advanced {concept} techniques",
        f"Best practices for {concept}",
        f"Common mistakes with {concept}"
    ]
